/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.cadastro;

import com.sistema.bean.Cliente;
import com.sistema.master.AppControleTI;
import com.sistema.controle.UltimoUsuarioLogin;
import com.sistema.controle.Log;
import com.sistema.controle.CadClienteListener;
import com.sistema.controle.Exceptions;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author comp1
 */
public class CadClienteJIF extends javax.swing.JInternalFrame {

    UltimoUsuarioLogin ultimoLogin = new UltimoUsuarioLogin();
    Log log;

    public CadClienteListener listener = new CadClienteListener(this);
    
    public CadClienteJIF() {
        initComponents();
        
        log = new Log("Usuario " + ultimoLogin.lerArquivo() + " acessou o Cadastro de Cliente em ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFEstado = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Clientes");

        jLabel1.setText("Código:");

        jTFCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Estado:");

        jBExcluir.setText("Excluir");
        jBExcluir.setActionCommand("Excluir");
        jBExcluir.addActionListener(listener);
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Gravar");
        jBCadastrar.setActionCommand("Cadastrar");
        jBCadastrar.addActionListener(listener);
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNome)
                    .addComponent(jTFEndereco)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBCadastrar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTFCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoFocusLost
        try {
            Cliente cliente;
            
            jTFCodigo.setText( jTFCodigo.getText().trim() );
            
            cliente = listener.procuraElemento();
            if ( cliente != null ){
                jTFNome.setText( cliente.getNome() );
                jTFEndereco.setText( cliente.getEndereco() );
                jTFBairro.setText( cliente.getBairro() );
                jTFCidade.setText( cliente.getCidade() );
                jTFEstado.setText( cliente.getEstado() );
            }else{
               jTFNome.setText("");
               jTFEndereco.setText("");
               jTFBairro.setText("");
               jTFCidade.setText("");
               jTFEstado.setText("");
            }
        } catch (Exceptions ex) {
            Logger.getLogger(CadLoginJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTFCodigoFocusLost

    public void inserirCliente( Integer linha ){
        AppControleTI.cliente[linha] = new Cliente(); 
        AppControleTI.cliente[linha].setCodigo(( Integer.valueOf(jTFCodigo.getText() )));
        AppControleTI.cliente[linha].setNome( jTFNome.getText() );
        AppControleTI.cliente[linha].setEndereco( jTFEndereco.getText() );
        AppControleTI.cliente[linha].setBairro( jTFBairro.getText() );
        AppControleTI.cliente[linha].setCidade( jTFCidade.getText() );
        AppControleTI.cliente[linha].setEstado( jTFEstado.getText() );
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    public String getCod() {
        String conteudo = jTFCodigo.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void setCod(String dados , CadClienteJIF stance) {
         stance.jTFCodigo.setText(dados);
    }
     
    public String getNome() {
        String conteudo = jTFNome.getText();
        if(conteudo.length() != 0 ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void setNome(String dados, CadClienteJIF stance) {
         stance.jTFNome.setText(dados);
    }
    
    public String getEndereco() {
        String conteudo = jTFEndereco.getText();
        if(conteudo.length() != 0 ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void setEndereco(String dados, CadClienteJIF stance) {
         stance.jTFEndereco.setText(dados);
    }
    
    public String getBairro() {
        String conteudo = jTFBairro.getText();
        if(conteudo.length() != 0 ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void setBairro(String dados, CadClienteJIF stance) {
         stance.jTFBairro.setText(dados);
    }
    
    public String getCidade() {
        String conteudo = jTFCidade.getText();
        if(conteudo.length() != 0 ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void setCidade(String dados, CadClienteJIF stance) {
         stance.jTFCidade.setText(dados);
    }
    
    public String getEstado() {
        String conteudo = jTFEstado.getText();
        if(conteudo.length() != 0 ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

    public void getEstado(String dados, CadClienteJIF stance) {
         stance.jTFEstado.setText(dados);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
    
    public void LimpaForm() {
        jTFNome.setText("");
        jTFCodigo.setText("");
        jTFBairro.setText("");
        jTFCidade.setText("");
        jTFEndereco.setText("");
        jTFEstado.setText("");
    }
    
    public void SetConsulta( String asNome, String asBairro, String asCidade, String asEndereco, String asEstado ) {
        jTFNome.setText(asNome);
        jTFBairro.setText(asBairro);
        jTFCidade.setText(asCidade);
        jTFEndereco.setText(asEndereco);
        jTFEstado.setText(asEstado);
    }
}
