/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.cadastro;

import com.sistema.bean.Login;
import com.sistema.master.AppControleTI;
import com.sistema.controle.UltimoUsuarioLogin;
import com.sistema.controle.Log;
import com.sistema.controle.CadLoginListener;
import com.sistema.controle.Exceptions;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;

/**
 *
 * @author comp1
 */
public class CadLoginJIF extends javax.swing.JInternalFrame {

    UltimoUsuarioLogin ultimoLogin = new UltimoUsuarioLogin();
    Log log;

    public CadLoginListener listener = new CadLoginListener(this);
    
    public CadLoginJIF() {
        initComponents();
        
        log = new Log("Usuario " + ultimoLogin.lerArquivo() + " acessou o Cadastro de Acessos em ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        jBCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jTFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Acesso ao Sistema");

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        jBCadastrar.setText("Gravar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Código:");

        jTFCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoFocusLost(evt);
            }
        });
        jTFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(9, 9, 9)
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(11, 11, 11)
                            .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2)
                            .addGap(6, 6, 6)
                            .addComponent(jPFSenha))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir)
                    .addComponent(jBCadastrar))
                .addContainerGap())
        );

        jBCadastrar.setActionCommand("Cadastrar");
        jBCadastrar.addActionListener(listener);
        jBExcluir.setActionCommand("Excluir");
        jBExcluir.addActionListener(listener);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
      
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jTFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoActionPerformed

    private void jTFCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoFocusLost
        try {
            Login login;
            
            jTFCodigo.setText( jTFCodigo.getText().trim() );
            
            login = listener.procuraElemento();
            if ( login != null ){
                jTFNome.setText( login.getNome() );
                jTFLogin.setText( login.getLogin() );
                jPFSenha.setText( login.getSenha() );
            }else{
               jTFNome.setText("");
               jPFSenha.setText("");
               jTFLogin.setText("");
            }
        } catch (Exceptions ex) {
            Logger.getLogger(CadLoginJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTFCodigoFocusLost
    
     public void setPosicao() {
            Dimension d = this.getDesktopPane().getSize();
            this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
     
    public String getCod() {
        String conteudo = jTFCodigo.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

     public void setCod(String dados , CadLoginJIF stance) {
         stance.jTFCodigo.setText(dados);
    }
     
     public String getNome() {
        String conteudo = jTFNome.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

     public void setNome(String dados , CadLoginJIF stance) {
         stance.jTFNome.setText(dados);
    }
     
     public String getLogin() {
        String conteudo = jTFLogin.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

     public void setLogin(String dados , CadLoginJIF stance) {
         stance.jTFLogin.setText(dados);
    }
     
     public String getSenha() {
        String conteudo = String.valueOf(jPFSenha.getPassword());
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }

     public void setSenha(String dados , CadLoginJIF stance) {
         stance.jPFSenha.setText(dados);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
    
    public void LimpaForm() {
        jTFNome.setText("");
        jTFCodigo.setText("");
        jPFSenha.setText("");
        jTFLogin.setText("");
    }
    
    public void SetConsulta( String asNome, String asSenha, String asLogin ) {
        jTFNome.setText(asNome);
        jPFSenha.setText(asSenha);
        jTFLogin.setText(asLogin);
    }
}
