/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.cadastro;

import com.sistema.bean.Servico;
import com.sistema.master.AppControleTI;
import com.sistema.controle.UltimoUsuarioLogin;
import com.sistema.controle.Log;
import com.sistema.controle.CadServicoListener;
import com.sistema.controle.Exceptions;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.java2d.SurfaceData;

/**
 *
 * @author comp1
 */
public class CadServicoJIF extends javax.swing.JInternalFrame {

    UltimoUsuarioLogin ultimoLogin = new UltimoUsuarioLogin();
    Log log;

    public CadServicoListener listener = new CadServicoListener(this);
    
    public CadServicoJIF() {
        initComponents();
        
        log = new Log("Usuario " + ultimoLogin.lerArquivo() + " acessou o Cadastro de Serviços em ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jTFValor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFTempo = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Serviços");

        jLabel3.setText("Código:");

        jTFCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoFocusLost(evt);
            }
        });

        jLabel4.setText("Descrição:");

        jTFDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDescricaoActionPerformed(evt);
            }
        });

        jTFValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFValorActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor:");

        jLabel6.setText("Tempo médio:");

        jTFTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTempoActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Gravar");
        jBCadastrar.setActionCommand("Cadastrar");
        jBCadastrar.addActionListener(listener);
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.setActionCommand("Excluir");
        jBExcluir.addActionListener(listener);
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)
                                .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBExcluir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDescricaoActionPerformed

    private void jTFValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFValorActionPerformed

    private void jTFTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTempoActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
      
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jTFCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoFocusLost
        try {
            Servico servico;
            
            jTFCodigo.setText( jTFCodigo.getText().trim() );
            
            servico = listener.procuraElemento();
            if ( servico != null ){
                jTFDescricao.setText( servico.getDescricao());
                jTFValor.setText( String.valueOf( servico.getValor()) );
                jTFTempo.setText( String.valueOf( servico.getTempoMedio()));
            }else{
               jTFDescricao.setText("");
               jTFValor.setText("");
               jTFTempo.setText("");
            }
        } catch (Exceptions ex) {
            Logger.getLogger(CadLoginJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTFCodigoFocusLost

    public void inserirLogin( Integer linha ){
        AppControleTI.servico[linha] = new Servico();
        AppControleTI.servico[linha].setCodigo(( Integer.valueOf(jTFCodigo.getText())));
        AppControleTI.servico[linha].setDescricao(jTFDescricao.getText());
        AppControleTI.servico[linha].setValor(Double.valueOf(jTFValor.getText()));
        AppControleTI.servico[linha].setTempoMedio(Integer.valueOf( jTFTempo.getText()));
    }
    
    public void setPosicao() {
            Dimension d = this.getDesktopPane().getSize();
            this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    public String getCod() {
        String conteudo = jTFCodigo.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }
    
    public void setCod(String dados , CadServicoJIF stance) {
         stance.jTFCodigo.setText(dados);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFTempo;
    private javax.swing.JTextField jTFValor;
    // End of variables declaration//GEN-END:variables

    public void LimpaForm() {
        jTFDescricao.setText("");
        jTFCodigo.setText("");
        jTFTempo.setText("");
        jTFValor.setText("");
    }
    
    public void SetConsulta( String asDescricao, String asTempo, String asValor ) {
        jTFDescricao.setText(asDescricao);
        jTFTempo.setText(asTempo);
        jTFValor.setText(asValor);
    }
    
    public String getDescricao() {
        String conteudo = jTFDescricao.getText();
        if(conteudo.length() != 0 || conteudo != null ){
            return conteudo;
        }else{
            return conteudo="";
        }
    }
    
    public void setDescricao(String dados , CadServicoJIF stance) {
         stance.jTFDescricao.setText(dados);
    }
    
    public Double getValor() {
        Double conteudo;

        if (jTFValor.getText().length() == 0) {
            conteudo = 0.00;
        }else{
            conteudo = Double.valueOf(jTFValor.getText());   
        }
        
        return conteudo;
    }
    
    public void setValor(Double dados , CadServicoJIF stance) {        
         stance.jTFValor.setText(String.valueOf(dados));
    }
    
    public Double getTempo() {
        Double conteudo;
        
        if (jTFTempo.getText().length() == 0) {
            conteudo = 0.00;
        }else{
            conteudo = Double.valueOf(jTFTempo.getText());
        }
            
        return conteudo;
    }
    
    public void setTempo(double dados , CadServicoJIF stance) {
         stance.jTFTempo.setText(String.valueOf(dados));
    }
}
